/**
 * Component registry for Voice Canvas — lazy-loaded from design system.
 *
 * Uses dynamic import('copernicus-ds') with a literal string so Vite
 * resolves it at build time, but the import only executes when loadRegistry()
 * is called (not at module evaluation time). This prevents crashes from
 * module-level side effects.
 *
 * Generated by story-ui init. Regenerate with: npx story-ui registry
 */

export const registry: Record<string, any> = {};

let _loaded = false;

export async function loadRegistry(): Promise<Record<string, any>> {
  if (_loaded) return registry;

  try {
    const mod = await import('copernicus-ds');

    for (const [key, value] of Object.entries(mod)) {
      if (/^[A-Z]/.test(key) && (typeof value === 'function' || typeof value === 'object')) {
        registry[key] = value;
      }
    }

    _loaded = true;
    console.log(`[componentRegistry] Loaded ${Object.keys(registry).length} components from copernicus-ds`);
  } catch (err) {
    console.error('[componentRegistry] Failed to load design system:', err);
  }

  return registry;
}

export default registry;
